### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by artamonJr** [romengrus/hotel-booking-template#3]
![image](https://user-images.githubusercontent.com/46949445/83749673-b7e2e300-a66c-11ea-9424-2b3c144c085f.png)
и у календаря по макету нету треугольника вверху

![image](https://user-images.githubusercontent.com/46949445/83749473-705c5700-a66c-11ea-83c2-7c0ade751865.png)
и кнопки должны появляться сразу при открытии дропдауна

Почему на странице регистрации съехал значок fb? Футер на всех страницах одинаковый ведь)
![image](https://user-images.githubusercontent.com/46949445/83749957-38094880-a66d-11ea-9134-77c583862391.png)

![image](https://user-images.githubusercontent.com/46949445/83752957-165e9000-a672-11ea-860e-7d027908d721.png)

![image](https://user-images.githubusercontent.com/46949445/83753038-38581280-a672-11ea-8959-ca0d56d996c4.png)

![image](https://user-images.githubusercontent.com/46949445/83753099-532a8700-a672-11ea-808c-cd39e1a028ce.png)
Также, убери лишние пункты)

![image](https://user-images.githubusercontent.com/46949445/83753267-a69cd500-a672-11ea-8e79-dc1c7e55109d.png)

![image](https://user-images.githubusercontent.com/46949445/83753398-e06ddb80-a672-11ea-9e3c-ac281e5eabf8.png)

**Comment by romengrus** [comment]
> Почему на странице регистрации съехал значок fb? Футер на всех страницах одинаковый ведь)

На странице регистрации расположение и размеры иконок соц сетей отличаются от других страниц. Хотя отличия и не значительные, но возможно в этом причина. Поправил немного стили, чтобы сходилось по максимому.

![social-icons-on-all-pages](https://user-images.githubusercontent.com/9342135/83939640-ca7d2980-a7de-11ea-8331-af27e1055eb7.png)

![social-icons-on-registration-page](https://user-images.githubusercontent.com/9342135/83939641-cbae5680-a7de-11ea-8f06-276d5d112b8a.png)

**Comment by romengrus** [comment]
Исправил все по pixel-perfect
