### ISSUE TITLE
bugs/ui

### ISSUE THREAD

**Issue by artamonJr** [romengrus/hotel-booking-template#4]
Переделай меню в хедере в соответствии с 8 [пунктом](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/errors.md) стандартов

Почему пункт жирный?
![image](https://user-images.githubusercontent.com/46949445/83753774-8f121c00-a673-11ea-9ea1-940dd6fc268a.png)

У мобильного меню задумка классная, но реализовано оно криво.
Во-первых 2 кнопки для закрытия? Зачем?
Во-вторых появляется горизонтальная полоса прокрутки и огромная часть серого фона
В-третьих пропадают ссылки "войти" и "зарегистрироваться". Пользователю на мобилке не нужно входить на сайт?)
![Peek 2020-06-04 14-58](https://user-images.githubusercontent.com/46949445/83754106-165f8f80-a674-11ea-92f7-960f7ed9f0f8.gif)

На главной странице появляется горизонтальная полоса прокрутки, нужно исправить. Попробуй подергай окошко
![image](https://user-images.githubusercontent.com/46949445/83754706-157b2d80-a675-11ea-953d-81751553b50f.png)

**Comment by madnessJs** [comment]
Это интерактивный элемент. Мы на него нажимаем, поэтому, в этом случае, должен быть выполнен в виде кнопки.
![image](https://user-images.githubusercontent.com/46949445/73938544-88a7a980-48f8-11ea-8d26-424582a22b1b.png)

**Comment by madnessJs** [comment]
Кнопки в хедере выполнены кнопками, что тоже не верно
![image](https://user-images.githubusercontent.com/46949445/73938663-c73d6400-48f8-11ea-9f17-47c7c6cf81e4.png)

**Comment by madnessJs** [comment]
Вообщем пробегись еще раз по стандартам и отрефактори по 2 кругу)

**Comment by artamonJr** [comment]
Пустое пространство при открытии мобильного меню никуда не пропало
Стрелочка от пункта с подменю куда-то сползла
![image](https://user-images.githubusercontent.com/46949445/84375429-377e2e00-abe8-11ea-84c2-50974e5e87e7.png)

**Comment by romengrus** [comment]
Исправил баги с мобильным меню. Но почему то когда просматриваешь в dev tool (в режиме mobile view), то все равно появляется полоса прокрутки. Решения для этого случая не нашел, но думаю главное чтобы правильно отображалось в нормальном режиме.

**Comment by artamonJr** [comment]
> Решения для этого случая не нашел, но думаю главное чтобы правильно отображалось в нормальном режиме.

Да, пока это оставим. Но все равно, как будет время, поковыряйся и попробуй исправить. Как никак это баг

Почему тут было выбрано поведение, что при нажатии на заголовок к полю, показывается календарь? Как мне кажется, тут специально стрелку сделали, чтобы нажатие на нее, а не на поле, открывало календарь
И граница инпута не должна появляется при hover'е, тк это тоже запутывает. Граница по наведению сигнализирует о том, что на это поле можно нажать и там можно писать, но тут иное поведение заложено
![image](https://user-images.githubusercontent.com/46949445/85138341-4483c880-b24b-11ea-9e21-c733dabf9818.png)

В дропдауне заложено другое поведение
(макет)
![image](https://user-images.githubusercontent.com/46949445/85138556-a5ab9c00-b24b-11ea-8d5b-8faaaac8e7ad.png)
(твой)
![image](https://user-images.githubusercontent.com/46949445/85138657-cf64c300-b24b-11ea-89b0-90c877bdef00.png)

Т.е. у нас есть, к примеру, 1 взрослый, 1 ребенок и 1 младенец, в итоге = 3 гостя, 1 младенец

У этого компонента есть описанное в макете состояние по наведению
![image](https://user-images.githubusercontent.com/46949445/85138717-eacfce00-b24b-11ea-8d3a-2f2bd10a409c.png)

У этой кнопки разнИца поведение с макетной кнопкой
![image](https://user-images.githubusercontent.com/46949445/85138816-2074b700-b24c-11ea-9faf-16186761a347.png)

Текст в инпутах не по макету
![image](https://user-images.githubusercontent.com/46949445/85138883-3e421c00-b24c-11ea-8aa9-e4634081cd23.png)

Весь календарь нужно проверить в соответствии с макетом
![image](https://user-images.githubusercontent.com/46949445/85138966-616ccb80-b24c-11ea-9982-8a84ac4353c4.png)

Текст не по макету
![image](https://user-images.githubusercontent.com/46949445/85138993-70ec1480-b24c-11ea-876c-8b12d3cdce8d.png)

Тут тоже что-то не так, нужно сверить с макетом
![image](https://user-images.githubusercontent.com/46949445/85139095-97aa4b00-b24c-11ea-9fe4-d2c3e12fbb7f.png)
