### ISSUE TITLE
basic iteration (html, css, bem)

### ISSUE THREAD

**Issue by artamonJr** [romengrus/hotel-booking-template#7]
У тебя сейчас на страницу грузятся стили и скрипты всех компонентов, что в корне неверно по бэм. Каждый компонент самодостаточен в обе стороны, компоненту не нужно ничего, чего ему не нужно) Поэтому на главной странице не должно быть стилей и скриптов от пагинации к примеру, которая используется на странице поиска комнат. Мало того, что это не по бем, так это очень замедляет загрузку страницы. В твоем случае не настолько сильно, но представь если ты разрабатываешь огромный сервис? Пользователь будет ждать 10 секунд чтобы страница загрузилась или будет использовать другой сервис?
И best practice считается размещение скриптов в конце тега body
![image](https://user-images.githubusercontent.com/46949445/83746099-42284880-a667-11ea-8e32-f9e4889bfab5.png)

Почитай про этот [момент](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md) в наших best practices (4п.)

**Comment by artamonJr** [comment]
Уже лучше, но есть недочеты. 
Зачем тебе грузить два css файла, если можно объединить их в один?
И грузится один большой файл скрипта, что тоже противоречит бэм.
![image](https://user-images.githubusercontent.com/46949445/84373931-eec57580-abe5-11ea-8ef4-d1ac377e8187.png)

Я тоже использовал parcel и насколько помню, там все из коробки нормально работает. Ты намудрил возможно в конфиге что-то)

**Comment by romengrus** [comment]
Исправил сборку стилей и скриптов. Теперь на каждой странице подгружаются только нужные компоненты.
