### ISSUE TITLE
Адаптивность

### ISSUE THREAD

**Issue by Constantine-P** [romengrus/hotel-booking-template#8]
1. При ширине 320px значок закрытия меню находится за пределами экрана. На странице поиска с кнопкой "изменить параметры поиска" тоже самое
2. Если открыть мобильное меню, затем увеличить ширину окна - меню остается, и закрыть его можно только снова уменьшив окно.

**Comment by romengrus** [comment]
Случайно закрыл issue потому что использовал ключевое слово fix в сообщении коммита. (Не знал об этом раньше)
